default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_app2_development

test:
  <<: *default
  database: todo_app2_test

production:
  <<: *default
  database: todo_app2_production
  username: todo_app2
  password: <%= ENV['TODO_APP2_DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
